site_name: Nylas Python SDK Reference
theme:
   name: 'material'

nav:
  - Getting Started: index.md
  - Code Reference: reference/
  - Contributing: contributing.md
  - License: license.md

# Add plugins
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ nylas ]
  - gen-files:
      scripts:
        - scripts/generate-docs.py
  - literate-nav:
        nav_file: SUMMARY.md
